version: "3.3"

networks:
  loan-network:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      - loan-network

  database:
    image: postgres:12.1
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "6543:5432"
    networks:
      - loan-network